name: 'SBOM Generation'
description: 'Generate SBOM for the repository'
permissions:
  id-token: write
  contents: read
inputs:
  repository-name:
    description: 'The name of the repository'
    required: true
  path:
    description: 'The path to scan for generating SBOM'
    required: true
    default: '.'
  format:
    description: 'The format of the SBOM file'
    required: true
    default: 'spdx-json'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Generate SBOM
      uses: anchore/sbom-action@v0.15.11
      with:
        path: ${{ inputs.path }}
        format: ${{ inputs.format }}
        output-file: ${{ inputs.repository-name }}-sbom.spdx.json
    - name: Upload SBOM files
      uses: actions/upload-artifact@v4
      with:
        name: sbom-files
        path: |
          ${{ inputs.repository-name }}-sbom.spdx.json
